domain_path: C:\Users\germa\Documents\projects\FPGA\zynqNetworking\impl\vitis\platform_lwip\zynq_fsbl\zynq_fsbl_bsp
app_src_dir: C:\AMDDesignTools\2025.2\Vitis\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
lang: c
